### ISSUE TITLE
System.NullReferenceException in `BarcodeResult.GetHashCode()` still an issue in 1.5.9 with iOS

### ISSUE THREAD

**Issue by Cannedfood** [afriscic/BarcodeScanning.Native.Maui#106]
I saw that there was a fix in 1.5.9. committed, but our App is still crashing at the same location.

**Comment by afriscic** [comment]
I see the crash happens on iOS/MacOS.
Both `DisplayValue` and `RawValue` are bound to `PayloadStringValue` so i guess `PayloadStringValue` is null or empty, but this is very strange.
I'll update the code in next release to ignore this barcodes or to get the value from `PayloadData`.

Can you please share the barcode image and OS version where it crashes.

**Comment by markuspalme** [comment]
It happens when there are a lot of barcodes visible at the same time:

![image](https://github.com/user-attachments/assets/d5ef0f5f-872d-4055-8f98-db7c7ea65729)

iOS 18.1.

**Comment by markuspalme** [comment]
I think that this fix https://github.com/afriscic/BarcodeScanning.Native.Maui/pull/100 would still be of value - it makes the class `BarcodeResult` more robust.

**Comment by afriscic** [comment]
I'll do one more net8 release next week as there is a major AndroidX.Camera update so I have to update a few things.
What I have noticed is that I didn't have `<Nullable>enable</Nullable>` so I'll do a hardening on a dozen of possible null reference exceptions.

**Comment by breyed** [comment]
This is a related call stack (BarcodeScanning.Native.Maui 2.1.8):

```
Value cannot be null. (Parameter 'source') (System.ArgumentNullException)
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument )
   at System.Linq.Enumerable.Contains[AVCaptureOutput](IEnumerable`1 , AVCaptureOutput , IEqualityComparer`1 )
   at System.Linq.Enumerable.Contains[AVCaptureOutput](IEnumerable`1 , AVCaptureOutput )
   at BarcodeScanning.CameraManager.<Start>b__20_0()
   at CoreFoundation.DispatchQueue.static_dispatcher_to_managed(IntPtr context)
```
