### ISSUE TITLE
iOS 12.5.7 - [AVCaptureSession startRunning] startRunning may not be called between calls to beginConfiguration and commitConfiguration

### ISSUE THREAD

**Issue by UkeHa** [afriscic/BarcodeScanning.Native.Maui#21]
Running the scanner with .net8 and the latest dll the app is unable to request the camera permissions and throws this error:[AVCaptureSession startRunning] startRunning may not be called between calls to beginConfiguration and commitConfiguration.

It then crashes the app. Restarting and trying to access the camera again results in another error:
+[AVCaptureDevice defaultDeviceWithDeviceType:mediaType:position:] The deviceType cannot be nil

<details><summary>Details</summary>
<p>
Thread started:  #14
**ObjCRuntime.ObjCException:** 'Objective-C exception thrown.  Name: NSGenericException Reason: *** -[AVCaptureSession startRunning] startRunning may not be called between calls to beginConfiguration and commitConfiguration
Native stack trace:
	0   CoreFoundation                      0x00000001ac72e198 <redacted> + 252
	1   libobjc.A.dylib                     0x00000001ab9069f8 objc_exception_throw + 56
	2   AVFoundation                        0x00000001b2770e54 <redacted> + 212
	3   W3AppMaui                           0x0000000100082044 xamarin_get_original_working_directory_path + 8604
	4   W3AppMaui                           0x00000001003ae20c AppleCryptoNative_X509ImportCollection + 2885204
	5   W3AppMaui                           0x00000001003acba8 AppleCryptoNative_X509ImportCollection + 2879472
	6   W3AppMaui                           0x00000001003a15b4 AppleCryptoNative_X509ImportCollection + 2832892
	7   W3AppMaui                           0x000000010039f180 AppleCryptoNative_X509ImportCollection + 2823624
	8   W3AppMaui                           0x000000010036de0c AppleCryptoNative_X509ImportCollection + 2622036
	9   W3AppMaui                           0x00000001003155d8 AppleCryptoNative_X509ImportCollection + 2259488
	10  W3AppMaui                           0x000000010031935c AppleCryptoNative_X509ImportCollection + 2275236
	11  W3AppMaui                           0x00000001003df944 AppleCryptoNative_X509ImportCollection + 3087756
	12  W3AppMaui                           0x000000010043a82c AppleCryptoNative_X509ImportCollection + 3460212
	13  Foundation                          0x00000001ad1b5690 <redacted> + 336
	14  CoreFoundation                      0x00000001ac6bff1c <redacted> + 24
	15  CoreFoundation                      0x00000001ac6bfe9c <redacted> + 88
	16  CoreFoundation                      0x00000001ac6bf784 <redacted> + 176
	17  CoreFoundation                      0x00000001ac6ba6c0 <redacted> + 1004
	18  CoreFoundation                      0x00000001ac6b9fb4 CFRunLoopRunSpecific + 436
	19  GraphicsServices                    0x00000001ae8bc79c GSEventRunModal + 104
	20  UIKitCore                           0x00000001d8b82c38 UIApplicationMain + 212
	21  W3AppMaui                           0x00000001000545f4 xamarin_UIApplicationMain + 60
	22  W3AppMaui                           0x00000001003ae2a8 AppleCryptoNative_X509ImportCollection + 2885360
	23  W3AppMaui                           0x00000001003acba8 AppleCryptoNative_X509ImportCollection + 2879472
	24  W3AppMaui                           0x00000001003a15b4 AppleCryptoNative_X509ImportCollection + 2832892
	25  W3AppMaui                           0x000000010039f180 AppleCryptoNative_X509ImportCollection + 2823624
	26  W3AppMaui                           0x000000010036de0c AppleCryptoNative_X509ImportCollection + 2622036
	27  W3AppMaui                           0x00000001003155d8 AppleCryptoNative_X509ImportCollection + 2259488
	28  W3AppMaui                           0x000000010031b8d4 AppleCryptoNative_X509ImportCollection + 2284828
	29  W3AppMaui                           0x0000000100373404 AppleCryptoNative_X509ImportCollection + 2644044
	30  W3AppMaui                           0x0000000100080fb8 xamarin_get_original_working_directory_path + 4368
	31  W3AppMaui                           0x00000001003db970 AppleCryptoNative_X509ImportCollection + 3071416
	32  libdyld.dylib                       0x00000001ac17d8e0 <redacted> + 4
'

Der Thread 0x8 hat mit Code 0 (0x0) geendet.
Der Thread 0x6 hat mit Code 0 (0x0) geendet.
Der Thread 0xd hat mit Code 0 (0x0) geendet.
Thread finished: <Thread Pool> #8
Thread finished: <Thread Pool> #6
Thread finished: <Thread Pool> #13
Thread started: <Thread Pool> #15
               0x00000001ac6b9fb4 CFRunLoopRunSpecific + 436
	19  GraphicsServices                    0x00000001ae8bc79c GSEventRunModal + 104
	20  UIKitCore                           0x00000001d8b82c38 UIApplicationMain + 212
	21  W3AppMaui                           0x00000001000545f4 xamarin_UIApplicationMain + 60
	22  W3AppMaui                           0x00000001003ae2a8 AppleCryptoNative_X509ImportCollection + 2885360
	23  W3AppMaui                           0x00000001003acba8 AppleCryptoNative_X509ImportCollection + 2879472
	24  W3AppMaui                           0x00000001003a15b4 AppleCryptoNative_X509ImportCollection + 2832892
	25  W3AppMaui                           0x000000010039f180 AppleCryptoNative_X509ImportCollection + 2823624
	26  W3AppMaui                           0x000000010036de0c AppleCryptoNative_X509ImportCollection + 2622036
	27  W3AppMaui                           0x00000001003155d8 AppleCryptoNative_X509ImportCollection + 2259488
	28  W3AppMaui                           0x000000010
031b8d4 AppleCryptoNative_X509ImportCollection + 2284828
	29  W3AppMaui                           0x0000000100373404 AppleCryptoNative_X509ImportCollection + 2644044
	30  W3AppMaui                           0x0000000100080fb8 xamarin_get_original_working_directory_path + 4368
	31  W3AppMaui                           0x00000001003db970 AppleCryptoNative_X509ImportCollection + 3071416
	32  libdyld.dylib                       0x00000001ac17d8e0 <redacted> + 4

   at AVFoundation.AVCaptureSession.StartRunning() in /Users/builder/azdo/_work/1/s/xamarin-macios/src/build/dotnet/ios/generated-sources/AVFoundation/AVCaptureSession.g.cs:line 270
   at BarcodeScanning.CameraViewHandler.Start()
   at BarcodeScanning.CameraViewHandler.HandleCameraEnabled()
   at BarcodeScanning.CameraViewHandler.<>c.<.cctor>b__27_4(CameraViewHandler handler, CameraView virtualView)
   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[BarcodeScanning.CameraView, BarcodeScanning.Native.Maui, Version=1.2.3.0, Culture=neutral, PublicKe
1ac72e198 <redacted> + 252
	1   libobjc.A.dylib                     0x00000001ab9069f8 objc_exception_throw + 56
	2   AVFoundation                        0x00000001b2770e54 <redacted> + 212
	3   W3AppMaui                           0x0000000100082044 xamarin_get_original_working_directory_path + 8604
	4   W3AppMaui                           0x00000001003ae20c AppleCryptoNative_X509ImportCollection + 2885204
	5   W3AppMaui                           0x00000001003acba8 AppleCryptoNative_X509ImportCollection + 2879472
	6   W3AppMaui                           0x00000001003a15b4 AppleCryptoNative_X509ImportCollection + 2832892
	7   W3AppMaui                           0x000000010039f180 AppleCryptoNative_X509ImportCollection + 2823624
	8   W3AppMaui                           0x000000010036de0c AppleCryptoNative_X509ImportCollection + 2622036
	9   W3AppMaui                           0x00000001003155d8 AppleCryptoNative_X509ImportCollection + 2259488
	10  W3AppMaui                           0x000000010031935c AppleCryp
toNative_X509ImportCollection + 2275236
	11  W3AppMaui                           0x00000001003df944 AppleCryptoNative_X509ImportCollection + 3087756
	12  W3AppMaui                           0x000000010043a82c AppleCryptoNative_X509ImportCollection + 3460212
	13  Foundation                          0x00000001ad1b5690 <redacted> + 336
	14  CoreFoundation                      0x00000001ac6bff1c <redacted> + 24
	15  CoreFoundation                      0x00000001ac6bfe9c <redacted> + 88
	16  CoreFoundation                      0x00000001ac6bf784 <redacted> + 176
	17  CoreFoundation                      0x00000001ac6ba6c0 <redacted> + 1004
	18  CoreFoundation                      0x00000001ac6b9fb4 CFRunLoopRunSpecific + 436
	19  GraphicsServices                    0x00000001ae8bc79c GSEventRunModal + 104
	20  UIKitCore                           0x00000001d8b82c38 UIApplicationMain + 212
	21  W3AppMaui                           0x00000001000545f4 xamarin_UIApplicationMain + 60
	22  W3AppMaui                        
2024-01-22 13:22:27.880 W3AppMaui[320:13416] 
Unhandled Exception:
ObjCRuntime.ObjCException: Objective-C exception thrown.  Name: NSGenericException Reason: *** -[AVCaptureSession startRunning] startRunning may not be called between calls to beginConfiguration and commitConfiguration
Native stack trace:
	0   CoreFoundation                      0x00000001ac72e198 <redacted> + 252
	1   libobjc.A.dylib                     0x00000001ab9069f8 objc_exception_throw + 56
	2   AVFoundation                        0x00000001b2770e54 <redacted> + 212
	3   W3AppMaui                           0x0000000100082044 xamarin_get_original_working_directory_path + 8604
	4   W3AppMaui                           0x00000001003ae20c AppleCryptoNative_X509ImportCollection + 2885204
	5   W3AppMaui                           0x00000001003acba8 AppleCryptoNative_X509ImportCollection + 2879472
	6   W3AppMaui                           0x00000001003a15b4 AppleCryptoNative_X509ImportCollection + 2832892
	7   W3AppMaui                          
 0x000000010039f180 AppleCryptoNative_X509ImportCollection + 2823624
	8   W3AppMaui                           0x000000010036de0c AppleCryptoNative_X509ImportCollection + 2622036
	9   W3AppMaui                           0x00000001003155d8 AppleCryptoNative_X509ImportCollection + 2259488
	10  W3AppMaui                           0x000000010031935c AppleCryptoNative_X509ImportCollection + 2275236
	11  W3AppMaui                           0x00000001003df944 AppleCryptoNative_X509ImportCollection + 3087756
	12  W3AppMaui                           0x000000010043a82c AppleCryptoNative_X509ImportCollection + 3460212
	13  Foundation                          0x00000001ad1b5690 <redacted> + 336
	14  CoreFoundation                      0x00000001ac6bff1c <redacted> + 24
	15  CoreFoundation                      0x00000001ac6bfe9c <redacted> + 88
	16  CoreFoundation                      0x00000001ac6bf784 <redacted> + 176
	17  CoreFoundation                      0x00000001ac6ba6c0 <redacted> + 1004
	18  CoreFoundation       
indableObject.SetValue(BindableProperty property, Object value)
   at BarcodeScanning.CameraView.set_CameraEnabled(Boolean value)
   at W3AppMaui.Views.BarcodeScanner.OnAppearing() in E:\sources\W3App\W3AppMaui\Views\BarCodeScanner.xaml.cs:line 29
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Foundation.NSAsyncSynchronizationContextDispatcher.Apply() in /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSAction.cs:line 176
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 58
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 94
   at W3AppMaui.Program.Main(String[] args) in E:\sources\W3App\W3AppMaui\Platforms\iOS\Program.cs:line 13
Native stack trace:
	0   CoreFoundation                      0x0000000
yToken=null],[BarcodeScanning.CameraViewHandler, BarcodeScanning.Native.Maui, Version=1.2.3.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v)
   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.PropertyMapper.UpdateProperty(IElementHandler viewHandler, IElement virtualView, String property)
   at Microsoft.Maui.Handlers.ElementHandler.UpdateValue(String property)
   at Microsoft.Maui.Controls.Element.OnPropertyChanged(String propertyName)
   at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, SetterSpecificity specificity, Boolean silent)
   at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes, SetterSpecificity specificity)
   at Microsoft.Maui.Controls.B
ntrols.BindableObject.SetValue(BindableProperty property, Object value)
   at BarcodeScanning.CameraView.set_CameraEnabled(Boolean value)
   at W3AppMaui.Views.BarcodeScanner.OnAppearing() in E:\sources\W3App\W3AppMaui\Views\BarCodeScanner.xaml.cs:line 29
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Foundation.NSAsyncSynchronizationContextDispatcher.Apply() in /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSAction.cs:line 176
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 58
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 94
   at W3AppMaui.Program.Main(String[] args) in E:\sources\W3App\W3AppMaui\Platforms\iOS\Program.cs:line 13

	0x1ac222ea8 - /usr/lib/system/libsystem_c.dylib : abort

7b c1 a8 c0 
ff 
fd 
	Managed Stacktrace:

..

=================================================================

.{....
.......T
7b bf a9 fd 03 00 91  
d4 c3 00 00 54 fd 
01 10 00 
)..
0x1ac2ca0fc  
Die App wurde beendet.
=================================================================
=================================================================

...
._..
.....{
90 29 
80 d2  
5f d6 
7b c1 a8 c0 
91 
03 
03 00 
..
0x1ac2ca0ec  bf 
...
.U.
..
..
.{
T
.
97 
55 d6 
......
0x1ac2ca0dc  c3 00 00 54 fd 7b bf a9 fd 
03 00 91 
 
..
._..
)
 .{.
10 00 d4 
01 
d2 
d6 10 29 80 
03 5f 
	0x10006e2c8 - /var/containers/Bundle/Application/D9D0FE60-19F1-48FB-9E21-BB3BF4BEC68B/W3AppMaui.app/W3AppMaui : xamarin_find_protocol_wrapper_type
	0x1002d35f4 - /var/containers/Bundle/Application/D9D0FE60-19F1-48FB-9E21-BB3BF4BEC68B/W3AppMaui.app/W3AppMaui : AppleCryptoNative_X509ImportCollection
	0x10037342c - /var/containers/Bundle/Application/D9D0FE60-19F1-48FB-9E21-BB3BF4BEC68B/W3AppMaui.app/W3AppMaui : AppleCryptoNative_X509ImportCollection
	0x100080fb8 - /var/containers/Bundle/Application/D9D0FE60-19F1-48FB-9E21-BB3BF4BEC68B/W3AppMaui.app/W3AppMaui : xamarin_get_original_working_directory_path
	0x1003db970 - /var/containers/Bundle/Application/D9D0FE60-19F1-48FB-9E21-BB3BF4BEC68B/W3AppMaui.app/W3AppMaui : AppleCryptoNative_X509ImportCollection
	0x1ac17d8e0 - /usr/lib/system/libdyld.dylib : <redacted>

=================================================================

	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x1ac2ca0dc):0x1ac2ca0cc  fd 
	0x1ac343094 - /usr/lib/system/libsystem_pthread.dylib : <redacted>

	0x1ac33d9fc - /usr/lib/system/libsystem_platform.dylib : <redacted>

	0x1004f3a74 - /var/containers/Bundle/Application/D9D0FE60-19F1-48FB-9E21-BB3BF4BEC68B/W3AppMaui.app/W3AppMaui : AppleCryptoNative_X509ImportCollection

	0x10039d210 - /var/containers/Bundle/Application/D9D0FE60-19F1-48FB-9E21-BB3BF4BEC68B/W3AppMaui.app/W3AppMaui : AppleCryptoNative_X509ImportCollection

=================================================================
	0x10039da20 - /var/containers/Bundle/Application/D9D0FE60-19F1-48FB-9E21-BB3BF4BEC68B/W3AppMaui.app/W3AppMaui : AppleCryptoNative_X509ImportCollection
	0x10038890c - /var/containers/Bundle/Application/D9D0FE60-19F1-48FB-9E21-BB3BF4BEC68B/W3AppMaui.app/W3AppMaui : AppleCryptoNative_X509ImportCollection

00001ac6b9fb4 CFRunLoopRunSpecific + 436
	19  GraphicsServices                    0x00000001ae8bc79c GSEventRunModal + 104
	20  UIKitCore                           0x00000001d8b82c38 UIApplicationMain + 212
	21  W3AppMaui                           0x00000001000545f4 xamarin_UIApplicationMain + 60
	22  W3AppMaui                           0x00000001003ae2a8 AppleCryptoNative_X509ImportCollection + 2885360
	23  W3AppMaui                           0x00000001003acba8 AppleCryptoNative_X509ImportCollection + 2879472
	24  W3AppMaui                           0x00000001003a15b4 AppleCryptoNative_X509ImportCollection + 2832892
	25  W3AppMaui                           0x000000010039f180 AppleCryptoNative_X509ImportCollection + 2823624
	26  W3AppMaui                           0x000000010036de0c AppleCryptoNative_X509ImportCollection + 2622036
	27  W3AppMaui                           0x00000001003155d8 AppleCryptoNative_X509ImportCollection + 2259488
	28  W3AppMaui                           0x000000010031b8d4 AppleCryptoN
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates

PublicKeyToken=null],[BarcodeScanning.CameraViewHandler, BarcodeScanning.Native.Maui, Version=1.2.3.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v)
   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.PropertyMapper.UpdateProperty(IElementHandler viewHandler, IElement virtualView, String property)
   at Microsoft.Maui.Handlers.ElementHandler.UpdateValue(String property)
   at Microsoft.Maui.Controls.Element.OnPropertyChanged(String propertyName)
   at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, SetterSpecificity specificity, Boolean silent)
   at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes, SetterSpecificity specificity)
   at Microsoft.Maui.Co
AppleCryptoNative_X509ImportCollection + 2823624
	8   W3AppMaui                           0x000000010036de0c AppleCryptoNative_X509ImportCollection + 2622036
	9   W3AppMaui                           0x00000001003155d8 AppleCryptoNative_X509ImportCollection + 2259488
	10  W3AppMaui                           0x000000010031935c AppleCryptoNative_X509ImportCollection + 2275236
	11  W3AppMaui                           0x00000001003df944 AppleCryptoNative_X509ImportCollection + 3087756
	12  W3AppMaui                           0x000000010043a82c AppleCryptoNative_X509ImportCollection + 3460212
	13  Foundation                          0x00000001ad1b5690 <redacted> + 336
	14  CoreFoundation                      0x00000001ac6bff1c <redacted> + 24
	15  CoreFoundation                      0x00000001ac6bfe9c <redacted> + 88
	16  CoreFoundation                      0x00000001ac6bf784 <redacted> + 176
	17  CoreFoundation                      0x00000001ac6ba6c0 <redacted> + 1004
	18  CoreFoundation                      0x000
2024-01-22 13:22:27.898 W3AppMaui[320:13416] Unhandled managed exception: Objective-C exception thrown.  Name: NSGenericException Reason: *** -[AVCaptureSession startRunning] startRunning may not be called between calls to beginConfiguration and commitConfiguration
Native stack trace:
	0   CoreFoundation                      0x00000001ac72e198 <redacted> + 252
	1   libobjc.A.dylib                     0x00000001ab9069f8 objc_exception_throw + 56
	2   AVFoundation                        0x00000001b2770e54 <redacted> + 212
	3   W3AppMaui                           0x0000000100082044 xamarin_get_original_working_directory_path + 8604
	4   W3AppMaui                           0x00000001003ae20c AppleCryptoNative_X509ImportCollection + 2885204
	5   W3AppMaui                           0x00000001003acba8 AppleCryptoNative_X509ImportCollection + 2879472
	6   W3AppMaui                           0x00000001003a15b4 AppleCryptoNative_X509ImportCollection + 2832892
	7   W3AppMaui                           0x000000010039f180 
509ImportCollection + 3071416
	32  libdyld.dylib                       0x00000001ac17d8e0 <redacted> + 4

ative_X509ImportCollection + 2284828
	29  W3AppMaui                           0x0000000100373404 AppleCryptoNative_X509ImportCollection + 2644044
	30  W3AppMaui                           0x0000000100080fb8 xamarin_get_original_working_directory_path + 4368
	31  W3AppMaui                           0x00000001003db970 AppleCryptoNative_X509ImportCollection + 3071416
	32  libdyld.dylib                       0x00000001ac17d8e0 <redacted> + 4
 (ObjCRuntime.ObjCException)
   at AVFoundation.AVCaptureSession.StartRunning() in /Users/builder/azdo/_work/1/s/xamarin-macios/src/build/dotnet/ios/generated-sources/AVFoundation/AVCaptureSession.g.cs:line 270
   at BarcodeScanning.CameraViewHandler.Start()
   at BarcodeScanning.CameraViewHandler.HandleCameraEnabled()
   at BarcodeScanning.CameraViewHandler.<>c.<.cctor>b__27_4(CameraViewHandler handler, CameraView virtualView)
   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[BarcodeScanning.CameraView, BarcodeScanning.Native.Maui, Version=1.2.3.0, Culture=neutral, 
   0x00000001003ae2a8 AppleCryptoNative_X509ImportCollection + 2885360
	23  W3AppMaui                           0x00000001003acba8 AppleCryptoNative_X509ImportCollection + 2879472
	24  W3AppMaui                           0x00000001003a15b4 AppleCryptoNative_X509ImportCollection + 2832892
	25  W3AppMaui                           0x000000010039f180 AppleCryptoNative_X509ImportCollection + 2823624
	26  W3AppMaui                           0x000000010036de0c AppleCryptoNative_X509ImportCollection + 2622036
	27  W3AppMaui                           0x00000001003155d8 AppleCryptoNative_X509ImportCollection + 2259488
	28  W3AppMaui                           0x000000010031b8d4 AppleCryptoNative_X509ImportCollection + 2284828
	29  W3AppMaui                           0x0000000100373404 AppleCryptoNative_X509ImportCollection + 2644044
	30  W3AppMaui                           0x0000000100080fb8 xamarin_get_original_working_directory_path + 4368
	31  W3AppMaui                           0x00000001003db970 AppleCryptoNative_X

</p>
</details>

**Comment by afriscic** [comment]
Hi. Please check if your camera permission was denied before. As per [documentation](https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/appmodel/permissions?view=net-maui-8.0&tabs=android#requesting-permissions), if you previously denied camera permission on iOS the prompt won't show on subsequent requests and you need to direct the user to grant camera permission in your own code.
As for 'The deviceType cannot be nil' error I'll implement additional checks in next release.

**Comment by UkeHa** [comment]
I've added the ask for permission in the OnAppearing of the method. This works fine for all later iOS versions as well as Android. The status is granted.

**Comment by UkeHa** [comment]
To add to the previous comment, the error is reproducable with your BarcodeScanning.Test project - the problem arises from this code in CameraViewHandler.cs

```c#
                    _captureDevice = AVCaptureDevice.GetDefaultDevice(AVCaptureDeviceType.BuiltInTripleCamera, AVMediaTypes.Video, AVCaptureDevicePosition.Back);
                    _captureDevice ??= AVCaptureDevice.GetDefaultDevice(AVCaptureDeviceType.BuiltInDualWideCamera, AVMediaTypes.Video, AVCaptureDevicePosition.Back);
                    _captureDevice ??= AVCaptureDevice.GetDefaultDevice(AVCaptureDeviceType.BuiltInDualCamera, AVMediaTypes.Video, AVCaptureDevicePosition.Back);
                    _captureDevice ??= AVCaptureDevice.GetDefaultDevice(AVCaptureDeviceType.BuiltInWideAngleCamera, AVMediaTypes.Video, AVCaptureDevicePosition.Back);
``` 

surrounding that code with a try/catch stops the app from crashing. After checking for the AuthorizationStatus getting the default device (like in your fallback code) produces a working camera output (for the back camera, front camera is unavailable and only returns a white image but no video output)

```c#
			var authStatus = AVCaptureDevice.GetAuthorizationStatus(AVAuthorizationMediaType.Video);
            if (authStatus == AVAuthorizationStatus.Authorized)
            {
                _captureDevice = AVCaptureDevice.GetDefaultDevice(AVMediaTypes.Video);
            }
``` 

Sadly, this still doesn't recognize any qrcodes, but at least it doesn't crash the app anymore. Do you have a hunch as to why barcode detection is dissociated to camera usage?

**Comment by afriscic** [comment]
Please try with 1.2.4 release. Hope it fixes the issue.
Unfortunately i don't have access to this older iOS version so i can't test directly.

**Comment by UkeHa** [comment]
will do tomorrow!

**Comment by UkeHa** [comment]
@afriscic the issue sadly isn't fixed in 1.2.4 - it requests permission and after accepting it still shuts down with the same error.

ObjCRuntime.ObjCException: 'Objective-C exception thrown.  Name: NSInvalidArgumentException Reason: *** +[AVCaptureDevice defaultDeviceWithDeviceType:mediaType:position:] The deviceType cannot be nil

This is due to "VirtualView?.CameraFacing => Expression not supported." which then runs the else-branch with the code mentioned above. If i remove: 

```c#
                    //_captureDevice = AVCaptureDevice.GetDefaultDevice(AVCaptureDeviceType.BuiltInTripleCamera, AVMediaTypes.Video, AVCaptureDevicePosition.Back);
                    //_captureDevice ??= AVCaptureDevice.GetDefaultDevice(AVCaptureDeviceType.BuiltInDualWideCamera, AVMediaTypes.Video, AVCaptureDevicePosition.Back);
``` 

from the else block in CameraViewHandler the camera works, but Barcode detection runs into an NSInvalidArgumentException in DidOutputSampleBuffer at:

```c#
_sequenceRequestHandler.Perform([_barcodeRequest], sampleBuffer, out _);
``` 
which skips to the catch block with this error:

```c#
Objective-C exception thrown.  Name: NSInvalidArgumentException Reason: -[VNSequenceRequestHandler performRequests:onCMSampleBuffer:error:]: unrecognized selector sent to instance 0x283f0d180
```

**Comment by afriscic** [comment]
I did a bit more research and found the culprits. As per Apple developer documentation AVCaptureDeviceType.BuiltInTripleCamera and BuiltInDualWideCamera are iOS 13+ ([link](https://developer.apple.com/documentation/avfoundation/avcapturedevice/devicetype/3377621-builtintriplecamera)) and SequenceRequestHandler.Perform on SampleBuffer is iOS 14+ ([link](https://developer.apple.com/documentation/vision/vnsequencerequesthandler/3571272-perform)). This is why it throws errors on iOS 12.
Unfortunately I'm unable to provide full support for legacy Android or iOS versions so i won't follow up on this.

**Comment by UkeHa** [comment]
Alright, I'd love to be able to support 12 and 13, but i guess i'll just block the barcode scanner in older versions.
